-- Address decode logic for ipbus fabric
-- 
-- This file has been AUTOGENERATED from the address table - do not hand edit
-- 
-- We assume the synthesis tool is clever enough to recognise exclusive conditions
-- in the if statement.
-- 
-- Dave Newbold, February 2011

library IEEE;
use IEEE.STD_LOGIC_1164.all;
use ieee.numeric_std.all;

package ipbus_decode_common is

  constant IPBUS_SEL_WIDTH: positive := 3;
  subtype ipbus_sel_t is std_logic_vector(IPBUS_SEL_WIDTH - 1 downto 0);
  function ipbus_sel_common(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t;

-- START automatically  generated VHDL the Fri Jul  3 13:37:08 2020 
  constant N_SLV_MODULE_ID: integer := 0;
  constant N_SLV_XMLVERSION: integer := 1;
  constant N_SLV_BUILDTIMEANDDATE: integer := 2;
  constant N_SLV_FIRMWAREVERSION: integer := 3;
  constant N_SLAVES: integer := 4;
-- END automatically generated VHDL

    
end ipbus_decode_common;

package body ipbus_decode_common is

  function ipbus_sel_common(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t is
    variable sel: ipbus_sel_t;
  begin

-- START automatically  generated VHDL the Fri Jul  3 13:37:08 2020 
    if    std_match(addr, "-----------------------------00-") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_MODULE_ID, IPBUS_SEL_WIDTH)); -- Module_ID / base 0x00000000 / mask 0x00000006
    elsif std_match(addr, "-----------------------------01-") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_XMLVERSION, IPBUS_SEL_WIDTH)); -- XmlVersion / base 0x00000002 / mask 0x00000006
    elsif std_match(addr, "-----------------------------10-") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_BUILDTIMEANDDATE, IPBUS_SEL_WIDTH)); -- BuildTimeAndDate / base 0x00000004 / mask 0x00000006
    elsif std_match(addr, "-----------------------------11-") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_FIRMWAREVERSION, IPBUS_SEL_WIDTH)); -- FirmwareVersion / base 0x00000006 / mask 0x00000006
-- END automatically generated VHDL

    else
        sel := ipbus_sel_t(to_unsigned(N_SLAVES, IPBUS_SEL_WIDTH));
    end if;

    return sel;

  end function ipbus_sel_common;

end ipbus_decode_common;

