######################################################################
#
# File name : TB_example_wave.do
# Created on: Tue Mar 31 15:31:14 CEST 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
# test