name: Hog
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    env:
      HOG_PATH: /opt/Xilinx/Vivado/2020.2/bin
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
         submodules: recursive
         ssh-key: ${{ secrets.HOG_KEY }}`
         fetch-depth: 0
    - name: Create Project
      run: |
              git submodule init
              git submodule update --remote 
              export PATH=${HOG_PATH}:$PATH
              echo $PATH
              git fetch -p
              git --version
              cd Hog/ && git fetch -p
              cd ..
              ./Hog/CreateProject.sh example
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Create artifacts
        path: |
          Projects
          
      
            
