name: Hog
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    env:
      HOG_PATH: /opt/Xilinx/Vivado/2020.2/bin
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
        #          submodules: 'true'
          fetch-depth: 0
      - name: Checkout submodules      
        run: git submodule update --init --recursive
      - run: echo "PATH=${HOG_PATH}:$PATH" >> $GITHUB_ENV
      - run: echo $PATH
      - run: git fetch -p
      - run: git --version
      - run: cd Hog/ && git tag -v
      - run: ./Hog/CreateProject.sh example
      
      
