name: Hog
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    env:
      HOG_PATH: /opt/Xilinx/Vivado/2020.2/bin
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          submodules: 'true'
          fetch-depth: 0
      - run: |
                echo "PATH=${HOG_PATH}:$PATH" >> $GITHUB_ENV
                echo $PATH
                git fetch -p
                git --version
                cd Hog/ && git tag -v
                cd ..
                ./Hog/CreateProject.sh example
      
      
