name: Deploy

on:
  pull_request:
    branches: [ master, main ]

jobs:
  hog-workflow:
    uses: hog-CERN/hog-workflows/.github/workflows/pull-request.yml@main
    secrets:
      SUBMODULE_CONTENT_PULL_KEY: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY  }}
    with:
      BUILD_PROJECTS: >-
        ["example", "proj.1"]
    