name: Deploy

on:
  pull_request:
    branches: [ master, main ]

jobs:
  hog-workflow:
    uses: hog-CERN/hog-workflows/.github/workflows/pull-request.yml@main
    secrets:
      SUBMODULE_CONTENT_PULL_KEY: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY  }}
      HOG_TOKEN: ${{ secrets.HOG_TOKEN }}
      HOG_MAIL: ${{ secrets.HOG_MAIL}}
      HOG_USER: ${{ secrets.HOG_USER}}
      HOG_PATH: /opt/Xilinx/Vivado/2020.2/bin
      HOG_CHECK_PROJVER: 1
    with:
      BUILD_PROJECTS: >-
        ["example", "proj.1"]
    