name: Hog
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    env:
      HOG_PATH: /opt/Xilinx/Vivado/2020.2/bin
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
         submodules: recursive
         fetch-depth: 0
    - run: |
              git submodule init
              git submodule update  
              export PATH=${HOG_PATH}:$PATH
              echo $PATH
              git fetch -p
              git --version
              cd Hog/ && git tag -v
              cd ..
              ./Hog/CreateProject.sh example
      
      
