name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  call-workflow-passing-data:
    uses: hog-CERN/Hog/YAML/GitHub/hog.yml@144-hog4github
    with:
      PROJECT_NAME: example
    secrets:
      SUBMODULE_CONTENT_PULL_KEY: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY  }}