name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  call-workflow-passing-data:
    uses: hog-CERN/hog-workflow/.github/workflows/hog.yml@main
    with:
      PROJECT_NAME: example
    secrets:
      SUBMODULE_CONTENT_PULL_KEY: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY  }}