name: Hog
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: 'true'
      - run: ./Hog/CreateProject.sh example
      
