name: Deploy

on:
  pull_request:
    branches: [ master, main ]

jobs:
  call-workflow-passing-data:
    uses: hog-CERN/hog-workflows/.github/workflows/merge-and-tag.yml@main
    secrets:
      SUBMODULE_CONTENT_PULL_KEY: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY  }}