name: Deploy

on:
  push:
    branches: 
      - master
      - develop

jobs:
  hog-workflow:
    uses: hog-CERN/Hog/.github/workflows/Hog-main.yml@270-non-eos-path-to-archive-binary-files
    secrets:
      SUBMODULE_CONTENT_PULL_KEY: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY  }}
      HOG_PUSH_TOKEN: ${{ secrets.HOG_PUSH_TOKEN }}
      HOG_EMAIL: ${{ secrets.HOG_EMAIL}}
      HOG_USER: ${{ secrets.HOG_USER}}
      EOS_USER: ${{ secrets.EOS_USER}}
      EOS_PASSWORD: ${{ secrets.EOS_PASSWORD}}
    with:
      HOG_CREATE_OFFICIAL_RELEASE: True
      HOG_BIN_EOS_PATH: "/eos/user/h/hog/www/firmware/github/official/"
