name: Main

on:
  push:
    branches: 
      - master
      - develop

jobs:
  hog-workflow:
    uses: hog-CERN/Hog/.github/workflows/Hog-main.yml@bdbb143034b93c461e5b0b1bf72d722f952060d7
    secrets:
      HOG_PUSH_TOKEN: ${{ secrets.HOG_PUSH_TOKEN }}
      HOG_EMAIL: ${{ secrets.HOG_EMAIL}}
      HOG_USER: ${{ secrets.HOG_USER}}

