name: Deploy

on:
  push:
    branches: 
      - main 
      - master
      - ${{ secrets.HOG_TARGET_BRANCH }}

jobs:
  hog-workflow:
    uses: hog-CERN/hog-workflows/.github/workflows/Hog-main.yml@main
    secrets:
      SUBMODULE_CONTENT_PULL_KEY: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY  }}
      HOG_PUSH_TOKEN: ${{ secrets.HOG_PUSH_TOKEN }}
      HOG_EMAIL: ${{ secrets.HOG_EMAIL}}
      HOG_USER: ${{ secrets.HOG_USER}}

    