name: Main

on:
  push:
    branches: 
      - master
      - develop

jobs:
  hog-workflow:
    uses: hog-CERN/Hog/.github/workflows/Hog-main.yml@66c1e01e492e8beaeab56fdee30d9d82f06c5a9a
    secrets:
      HOG_PUSH_TOKEN: ${{ secrets.HOG_PUSH_TOKEN }}
      HOG_EMAIL: ${{ secrets.HOG_EMAIL}}
      HOG_USER: ${{ secrets.HOG_USER}}

