name: Main

on:
  push:
    branches: 
      - master
      - develop

jobs:
  hog-workflow:
    uses: hog-CERN/Hog/.github/workflows/Hog-main.yml@4fc0c1d4b61a8c4a718cc763efb8e09b434a086a
    secrets:
      HOG_PUSH_TOKEN: ${{ secrets.HOG_PUSH_TOKEN }}
      HOG_EMAIL: ${{ secrets.HOG_EMAIL}}
      HOG_USER: ${{ secrets.HOG_USER}}

