name: Tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  hog-workflow:
    uses: hog-CERN/Hog/.github/workflows/Hog-tag.yml@bfd5672acca453ea9f712e3e39159ff764b21001
    secrets:
      HOG_PUSH_TOKEN: ${{ secrets.HOG_PUSH_TOKEN }}
      HOG_EMAIL: ${{ secrets.HOG_EMAIL}}
      HOG_USER: ${{ secrets.HOG_USER}}
      EOS_USER: ${{ secrets.EOS_USER}}
      EOS_PASSWORD: ${{ secrets.EOS_PASSWORD}}
    with:
      HOG_CREATE_OFFICIAL_RELEASE: True
      HOG_OFFICIAL_BIN_PATH: "/eos/user/h/hog/www/firmware/github/official/"
