name: Tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  hog-workflow:
    uses: hog-CERN/Hog/.github/workflows/Hog-tag.yml@abe13d6b50c3674742aad48b01812d49f00f3618
    secrets:
      HOG_PUSH_TOKEN: ${{ secrets.HOG_PUSH_TOKEN }}
      HOG_EMAIL: ${{ secrets.HOG_EMAIL}}
      HOG_USER: ${{ secrets.HOG_USER}}
      EOS_USER: ${{ secrets.EOS_USER}}
      EOS_PASSWORD: ${{ secrets.EOS_PASSWORD}}
    with:
      HOG_CREATE_OFFICIAL_RELEASE: "1"
      HOG_OFFICIAL_BIN_PATH: "/eos/user/h/hog/www/firmware/github/official/"
